import { Link } from 'react-router-dom';
import type { LegalDoc, LegalSection } from '../../components/landing/LegalPage';
import { External, Mail, UPDATED } from './shared';

const sections: LegalSection[] = [
  {
    id: 'who-we-are',
    title: 'Who we are',
    body: (
      <>
        <p>
          Flareboard (“Flareboard”, “we”, “us”) is a product analytics service operated by an independent
          developer. This policy covers the hosted service at <code>flareboard.dev</code>, including our website,
          the dashboard, the API (<code>api.flareboard.dev</code>) and the tracking endpoint{' '}
          (<code>t.flareboard.dev</code>). You can reach us about anything in this policy at <Mail />.
        </p>
        <p>
          Flareboard is also published as source code that anyone can run on their own infrastructure. If you use
          a self-hosted Flareboard, the person or organization running it decides how data is handled; we have no
          access to that data and this policy does not apply to it.
        </p>
      </>
    ),
  },
  {
    id: 'roles',
    title: 'Two kinds of data, two roles',
    body: (
      <>
        <p>We handle personal data in two different capacities:</p>
        <ul>
          <li>
            <strong>Customer data.</strong> Information about people who visit our website or create a Flareboard
            account (“customers”). For this data we decide why and how it is processed, so we act as the{' '}
            <strong>controller</strong>.
          </li>
          <li>
            <strong>Analytics data.</strong> Information our tracking script and APIs collect about visitors to our
            customers’ websites and apps (“visitors”). Our customers decide to install Flareboard and what to
            collect; we process this data only to provide the service to them. For analytics data the customer is
            the <strong>controller</strong> and we are a <strong>processor</strong> (or service provider) acting on
            the customer’s instructions, as set out in our <Link to="/terms#data-processing">Terms of Service</Link>.
          </li>
        </ul>
        <p>
          If you are a visitor to a website that uses Flareboard and want to exercise your privacy rights, please
          contact that website’s owner first. We will help them respond.
        </p>
      </>
    ),
  },
  {
    id: 'customer-data',
    title: 'Customer data we collect',
    body: (
      <>
        <h3>Account information</h3>
        <ul>
          <li>Email address (also used as your username), optional display name and logo.</li>
          <li>
            Your password, stored only as a salted bcrypt hash. We never store or see your password in plain text.
          </li>
          <li>
            If you sign in with Google or GitHub (when offered), the provider’s account identifier and the email or
            username the provider returns. We do not store the provider’s access tokens.
          </li>
          <li>Email verification status, role, team memberships and account timestamps.</li>
          <li>
            Personal API keys you create: their name, scopes, the first characters of the key and when it was
            created and last used. The full key is shown to you once and stored only as a one-way (SHA-256) hash.
            Revoking a key deletes it; the rest are erased with your account.
          </li>
        </ul>
        <h3>Billing information</h3>
        <p>
          Payments are handled by Stripe. Card details are entered on Stripe’s pages and never reach our servers.
          We receive and store your Stripe customer and subscription identifiers, plan, subscription status and
          billing period, and we send Stripe your email address and account identifier to create the subscription.
          We also count the events your websites send each month to apply plan limits.
        </p>
        <h3>Content you create</h3>
        <p>
          Websites, dashboards (“boards”), reports, insights, segments, cohorts, goals, feature flags, experiments,
          surveys, workflows, alert rules, saved queries, annotations, uploaded source maps and similar
          configuration you create in the dashboard.
        </p>
        <h3>Activity and security records</h3>
        <ul>
          <li>
            An audit log of administrative actions in your account (for example, creating or deleting a website),
            recording who did what and when. For feature flags it also keeps the flag’s settings before and after
            each change. It does not record IP addresses. Entries about a website are erased with that website.
          </li>
          <li>
            Technical logs generated by our hosting provider when our servers handle requests, such as request
            paths, status codes and error messages. These may contain IP addresses and are kept for a short period
            (see <a href="#retention">Retention</a>).
          </li>
          <li>
            IP addresses are used briefly for rate limiting and abuse prevention (for example, limiting sign-in
            attempts). We do not store them in our database.
          </li>
        </ul>
        <h3>Communications</h3>
        <p>Messages you send us, for example support emails, and our replies.</p>
      </>
    ),
  },
  {
    id: 'website-analytics',
    title: 'Analytics on our own website',
    body: (
      <>
        <p>
          We measure how people use <code>flareboard.dev</code> so we can improve it. We use two tools, neither of
          which sets cookies:
        </p>
        <ul>
          <li>
            <strong>Flareboard itself.</strong> Our own tracking script records the same kinds of data described in{' '}
            <a href="#analytics-data">Analytics data</a> below (pages viewed, referrer, browser, device type,
            approximate location), plus a small number of product events such as a successful sign-in.
          </li>
          <li>
            <strong>Cloudflare Web Analytics.</strong> Cloudflare measures page load performance and aggregate
            visits. See{' '}
            <External href="https://www.cloudflare.com/web-analytics/">Cloudflare Web Analytics</External>.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'analytics-data',
    title: 'Analytics data we process for customers',
    body: (
      <>
        <p>
          When a customer adds the Flareboard script or sends data through our APIs, we process the following on
          their behalf. Customers choose which features to enable, so not every site collects everything below.
        </p>
        <h3>Collected automatically by the tracking script</h3>
        <ul>
          <li>
            The page address (path, query string and fragment), page title and hostname, plus the referring page
            and any campaign parameters (such as <code>utm_source</code>) or ad click identifiers (such as{' '}
            <code>gclid</code>) present in the address.
          </li>
          <li>
            Browser, operating system and device type (derived from the user agent; the full user agent string is
            not stored), screen size and browser language.
          </li>
          <li>
            Approximate location (country, region and city), derived by our hosting provider from the IP address
            at the time of the request.
          </li>
          <li>Page performance metrics (Core Web Vitals), when enabled.</li>
          <li>Aggregated click positions for heatmaps, when enabled. Heatmap data is not linked to a visitor.</li>
          <li>
            <strong>Interactions (autocapture)</strong>, when the customer leaves it on: clicks on links and buttons,
            form submissions and changes to form fields. For each, the script records the kind of element, its
            identifier, name and CSS classes, the link address, a short description of its position in the page and
            up to 255 characters of its visible text. It <strong>never records what is typed or selected</strong> in
            a form field, never reads text from form fields, password fields or elements that look sensitive (for
            example payment or one-time-code fields), drops text that looks like a card number, identity number or
            email address, and records nothing inside parts of a page the customer marks as excluded.
          </li>
          <li>
            <strong>Page leave</strong>, together with autocapture: how long a page was visible and how far down it
            was scrolled.
          </li>
        </ul>
        <h3>How visitors are counted</h3>
        <div className="legal-callout">
          <p>
            <strong>IP addresses are never stored.</strong> To count unique visitors without cookies, we compute a
            one-way hash of the IP address, user agent, website identifier and a secret value. The secret value
            rotates at the start of each calendar month, so the same browser on the same network is counted as one
            visitor within a month but cannot be linked across months. The IP address itself is discarded once the
            request is handled.
          </p>
        </div>
        <p>
          <strong>Remembering visitors (off by default).</strong> A customer can turn on “Remember visitors across
          sessions” for a website. The script then creates a random identifier, keeps it in the browser’s{' '}
          <code>localStorage</code> and sends it with each event, and that identifier is used instead of the hash
          above to count the visitor. The same browser is then recognized across networks and months, until the
          visitor clears the site’s data or the website resets it (for example at sign-out). The identifier is
          random: it is not derived from the IP address or the device. IP addresses are still never stored.
          Because this stores an identifier on the visitor’s device, customers who turn it on are responsible for
          obtaining any consent the law where their visitors are requires.
        </p>
        <p>
          Customers can also send data with PostHog’s open-source SDKs (such as posthog-js or posthog-node)
          pointed at Flareboard. We process it as described on this page: IP address properties and raw user
          agent strings included in such data are discarded, not stored. Those SDKs may use cookies or{' '}
          <code>localStorage</code> on the customer’s site according to how the customer configures them.
        </p>
        <p>
          The tracking script sets <strong>no cookies</strong>. It keeps short-lived session information in the
          browser’s <code>sessionStorage</code>, which is cleared when the tab is closed. It uses{' '}
          <code>localStorage</code> only when a customer identifies a signed-in user or shows a survey (to
          remember that identifier or survey state), when a visitor opts out (to remember that choice), and, on
          websites that remember visitors, for the random visitor identifier and the event properties the website
          asks the script to attach to every event.
        </p>
        <h3>Data customers choose to send</h3>
        <ul>
          <li>
            <strong>Custom events and properties</strong>, including user identifiers and profile properties sent
            with <code>identify()</code>, group membership and revenue amounts. Customers control this content and
            may include personal data such as an email address. When a visitor opts in or out of an early access
            feature, that choice is stored as a property of their profile.
          </li>
          <li>
            <strong>Session replay</strong> (off by default; paid plans only). When a customer turns it on, the
            script records the structure of the page and the visitor’s interactions (clicks, scrolling, mouse
            movement and page changes) so the session can be replayed. By default, everything typed into form
            fields is masked, and password fields are always masked. Customers can exclude further parts of the
            page from recordings and record only a sample of visits. Other text shown on the page is recorded, so
            customers must configure replay not to capture sensitive information.
          </li>
          <li>
            <strong>Errors and logs</strong>: error messages, stack traces, release and environment names, and log
            messages with the data customers attach.
          </li>
          <li>
            <strong>Survey responses</strong>, including free-text answers visitors choose to submit. If a visitor
            closes a multi-question survey part-way, the answers already given are kept as a partial response.
            Customers can also share a hosted survey link that works without the tracking script. Answers sent there
            are stored the same way, together with any identifier the customer adds to the link, and the page
            remembers in the browser&apos;s <code>localStorage</code> that the survey was answered.
          </li>
          <li>
            <strong>AI usage data</strong>: model, token counts, cost and latency. Prompts and responses are only
            stored if a customer includes them in the data they send.
          </li>
        </ul>
        <p>
          The tracking script ignores most automated traffic (bots and crawlers). Customers can set a website to
          honor Do Not Track and Global Privacy Control browser signals, in which case the script sends nothing from
          browsers that send either signal. Websites can also offer visitors an opt-out; the choice is remembered in
          the browser and the script then sends nothing.
        </p>
        <p>
          We do not use analytics data for our own purposes, do not combine it across customers, and never sell it
          or use it for advertising.
        </p>
      </>
    ),
  },
  {
    id: 'use',
    title: 'How we use customer data',
    body: (
      <>
        <ul>
          <li>To create and secure your account, sign you in and provide the service you signed up for.</li>
          <li>To process payments, apply plan limits and manage your subscription.</li>
          <li>
            To send service emails: email verification, password resets, and alerts, reports or workflow emails
            you configure. We do not send marketing email without your consent, and you can opt out at any time.
          </li>
          <li>To answer support requests.</li>
          <li>To prevent abuse, fraud and security incidents, and to debug problems.</li>
          <li>To understand how the product is used, in aggregate, so we can improve it.</li>
          <li>To comply with legal obligations and enforce our Terms of Service.</li>
        </ul>
        <p>We do not sell personal data and do not share it with advertisers.</p>
      </>
    ),
  },
  {
    id: 'legal-bases',
    title: 'Legal bases (EEA and UK)',
    body: (
      <>
        <p>
          If you are in the European Economic Area or the United Kingdom, we rely on these legal bases for customer
          data:
        </p>
        <ul>
          <li>
            <strong>Contract</strong>: to provide the service, manage your account and process payments.
          </li>
          <li>
            <strong>Legitimate interests</strong>: to secure and improve the service, prevent abuse, measure use of
            our website and communicate with you about your account. We balance these interests against your
            rights, and you can object at any time.
          </li>
          <li>
            <strong>Legal obligation</strong>: to keep records required by tax and accounting law.
          </li>
          <li>
            <strong>Consent</strong>: where the law requires it, for example for optional marketing emails. You can
            withdraw consent at any time.
          </li>
        </ul>
        <p>For analytics data, the customer who installed Flareboard determines the legal basis.</p>
      </>
    ),
  },
  {
    id: 'cookies',
    title: 'Cookies and browser storage',
    body: (
      <>
        <div className="legal-table-wrap">
          <table className="legal-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Where</th>
                <th>Purpose</th>
                <th>Duration</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <code>flareboard_session</code>
                </td>
                <td>Dashboard (cookie)</td>
                <td>Keeps you signed in. Strictly necessary; HttpOnly and Secure.</td>
                <td>7 days</td>
              </tr>
              <tr>
                <td>
                  <code>__cf_bm</code>, <code>cf_clearance</code>
                </td>
                <td>All our domains (cookie)</td>
                <td>Set by Cloudflare to detect bots and protect the service. Strictly necessary.</td>
                <td>Up to 30 minutes / as set by Cloudflare</td>
              </tr>
              <tr>
                <td>Theme, language and interface preferences</td>
                <td>Dashboard (localStorage)</td>
                <td>Remembers your display choices.</td>
                <td>Until cleared</td>
              </tr>
              <tr>
                <td>
                  <code>flareboard.*</code>
                </td>
                <td>Websites using Flareboard (sessionStorage, localStorage)</td>
                <td>
                  Session information for the tracking script, as described in{' '}
                  <a href="#analytics-data">Analytics data</a>. No cookies.
                </td>
                <td>
                  Until the tab closes; identify, survey and opt-out state, and (when the website remembers visitors)
                  the random visitor identifier, until cleared
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>We do not use advertising or cross-site tracking cookies.</p>
      </>
    ),
  },
  {
    id: 'sharing',
    title: 'Service providers and sharing',
    body: (
      <>
        <p>We share personal data only with the service providers we need to run Flareboard:</p>
        <div className="legal-table-wrap">
          <table className="legal-table">
            <thead>
              <tr>
                <th>Provider</th>
                <th>Purpose</th>
                <th>Data</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Cloudflare, Inc.</td>
                <td>
                  Hosting, databases, file storage, queues, content delivery, security, email delivery, logs and
                  web analytics
                </td>
                <td>All customer and analytics data</td>
              </tr>
              <tr>
                <td>Stripe, Inc.</td>
                <td>Payments and subscription billing</td>
                <td>Email, account identifier, payment details (entered directly with Stripe)</td>
              </tr>
              <tr>
                <td>Google LLC, GitHub, Inc.</td>
                <td>Optional sign-in, only if you choose it</td>
                <td>Account identifier and email or username</td>
              </tr>
              <tr>
                <td>jsDelivr, unpkg, CARTO, Simple Icons</td>
                <td>Fonts, map data and icons loaded by your browser when you use the dashboard</td>
                <td>Your IP address and browser details, as part of the request</td>
              </tr>
              <tr>
                <td>favicon.so</td>
                <td>Shows the icon of each website in your dashboard</td>
                <td>The domain names of websites you add, plus your IP address as part of the request</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>We may also disclose personal data:</p>
        <ul>
          <li>
            <strong>At your direction</strong>, for example to webhook URLs, email addresses or data sources you
            configure, or through public share links you create. Anyone with a share link can see the aggregate
            statistics it exposes.
          </li>
          <li>
            <strong>For legal reasons</strong>, if required by law or a valid legal request, or to protect the
            rights, property or safety of our users, the public or us.
          </li>
          <li>
            <strong>In a business transfer</strong>, if Flareboard is sold or transferred, in which case this policy
            will continue to apply to your data.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'transfers',
    title: 'International transfers',
    body: (
      <p>
        Flareboard runs on Cloudflare’s global network, so data may be processed in data centers in many countries,
        including outside your own. Where the law requires it, we rely on appropriate safeguards for these
        transfers, such as the European Commission’s Standard Contractual Clauses included in our providers’ data
        processing terms.
      </p>
    ),
  },
  {
    id: 'retention',
    title: 'Retention and deletion',
    body: (
      <>
        <ul>
          <li>
            <strong>Account data</strong> is kept while your account is open. You can delete your account at any
            time from the account menu in the dashboard; it is closed immediately, and your account and content are
            permanently erased within 30 days.
          </li>
          <li>
            <strong>Billing records</strong> are kept for as long as tax and accounting law requires, generally
            seven years.
          </li>
          <li>
            <strong>Analytics data</strong> is kept until the customer deletes it or it expires under the data
            retention period the customer sets for each website (from 1 day to 10 years). By default there is no
            expiry. Session replay recordings are deleted together with the raw events they belong to. Aggregated
            statistics derived from raw events may be kept for the life of the website.
          </li>
          <li>
            <strong>Deleting a website</strong> in the dashboard removes it from your account immediately, and all
            of its stored data, including session replay recordings, is permanently erased within 30 days.
          </li>
          <li>
            <strong>Technical logs</strong> kept by our hosting provider are deleted automatically, typically within
            7 days.
          </li>
          <li>
            <strong>Backups.</strong> Deleted data may remain in database backups for up to 30 days before it is
            overwritten.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'rights',
    title: 'Your rights',
    body: (
      <>
        <p>
          Depending on where you live, you may have the right to access, correct, delete or export your personal
          data, to object to or restrict certain processing, and to withdraw consent. You can view and edit most
          account information in the dashboard, delete your account from the account menu, and paid plans can
          export analytics data as CSV. For anything else, email <Mail /> from the address on your account. We will
          respond within 30 days.
        </p>
        <p>
          If you are unhappy with how we handle your data, please tell us first. You also have the right to
          complain to your local data protection authority, such as a supervisory authority in the EEA, the UK
          Information Commissioner’s Office, or the Office of the Privacy Commissioner for Personal Data in Hong
          Kong.
        </p>
        <p>
          <strong>Visitors to customers’ websites:</strong> we do not hold a direct relationship with you and
          usually cannot identify you. Please contact the owner of the website you visited; we will assist them in
          responding to your request.
        </p>
      </>
    ),
  },
  {
    id: 'security',
    title: 'Security',
    body: (
      <p>
        We protect data with encryption in transit (HTTPS), the encryption at rest provided by our hosting
        provider, hashed passwords and API keys, encrypted and revocable session tokens, role-based access controls and rate
        limiting. No system is perfectly secure, however, and we cannot guarantee absolute security. If a breach
        affects your personal data, we will notify you and the relevant authorities as required by law.
      </p>
    ),
  },
  {
    id: 'children',
    title: 'Children',
    body: (
      <p>
        Flareboard is a business tool and is not directed at children. You must be at least 16 to create an
        account. We do not knowingly collect personal data from children; if you believe a child has given us
        personal data, contact us and we will delete it. Customers must not use Flareboard to collect data from
        children in violation of applicable law.
      </p>
    ),
  },
  {
    id: 'changes',
    title: 'Changes to this policy',
    body: (
      <p>
        We may update this policy as the service changes. We will change the “Last updated” date above, and if a
        change is significant we will notify customers by email or in the dashboard before it takes effect.
      </p>
    ),
  },
  {
    id: 'contact',
    title: 'Contact',
    body: (
      <p>
        Questions or requests about privacy: <Mail />.
      </p>
    ),
  },
];

export const privacyEn: LegalDoc = {
  title: 'Privacy Policy',
  updated: UPDATED.en,
  intro: (
    <p>
      This policy explains what personal data Flareboard collects, why, how long we keep it and the choices you
      have. We built Flareboard to measure websites without cookies and without storing IP addresses, and we
      try to collect as little as the service needs.
    </p>
  ),
  sections,
};
