import { FLAG_HASH_JS } from '@flareboard/shared';

/**
 * The browser tracker served at /script.js. Owned by the tracker-sdk stream (see
 * docs/parity/CONVENTIONS.md); other streams describe what they need instead of editing it.
 *
 * Behavior (documented here so none of it ships to browsers):
 * - Pageviews, including SPA routes: pushState/replaceState/popstate and hash routes (#/path).
 *   In-page anchors (#section) are not new pages. Hash routes keep the real ?query merged in.
 * - Declarative events (Umami-compatible): data-flareboard-event / data-umami-event.
 * - Autocapture ($autocapture): clicks on links, buttons, [role=button] and submit/button inputs,
 *   form submits, and change on input/select/textarea. Never records values. Text (<= 255 chars)
 *   is never read from fields, password or sensitive-looking elements, and nothing inside
 *   [data-fb-no-capture] / .ph-no-capture is captured at all. Throttled per page (burst of 10,
 *   refilling one per second, at most 100 per page, repeats within 1 s dropped). Follows the
 *   website setting; data-autocapture="false|true" overrides it per page.
 * - $pageleave: seconds the page was visible and max scroll depth, on SPA route changes and on
 *   pagehide (sendBeacon, keepalive fetch fallback). Follows autocapture unless data-pageleave.
 * - Identity: identify() ids live in localStorage (as before). When the website remembers
 *   visitors (tracker-config `persistence`), a random anonymous id is kept in localStorage and
 *   sent as the distinct id (`id` + `anonymousId`) until identify(), which aliases it to the user.
 *   Before the setting is known the id waits in sessionStorage; ingest ignores it on websites
 *   without persistence. data-persistence="false" keeps a page cookieless.
 * - Super properties: register / registerOnce / unregister, merged into every event's data
 *   (event data wins, 100 keys max). Stored like identity: localStorage when visitors are
 *   remembered, else sessionStorage.
 * - Opt-out: optOut / optIn / hasOptedOut (localStorage flag). Do Not Track / Global Privacy
 *   Control are honored when the website says so or data-respect-dnt is present; until the
 *   setting is known, sends from such browsers are held.
 * - Surveys (tracker-config `surveys[]`, `version: 2`): questions one at a time (rating 1-5,
 *   1-10 or NPS 0-10, single/multiple choice with "Other", open text, link), branching exactly
 *   like nextSurveyQuestion in @flareboard/shared (svNext; parity-tested), appearance position
 *   and light/dark/auto palette, thank-you step. One responseId per display; dismissing after an
 *   answer posts completed:false. Shown when hashFlag('survey:'+id+':'+bucket id) < sampleRate,
 *   at most once per person (or again after repeatIntervalDays; localStorage
 *   flareboard.survey:<id> holds the last-shown time), never after endsAt or when opted out.
 *   Legacy configs without version 2 render their single question.
 * - Heatmaps, errors, logs, AI observations, web vitals and feature flags as before.
 *   Feature flags bucket by distinct id, anonymous id, session id, visit id, 'anonymous'
 *   (flagBucketingId in @flareboard/shared) with the shared FLAG_HASH_JS.
 * - Calls made before the script loads (window.flareboard = { _q: [[method, args], ...] }, as
 *   the @flareboard/js loader does) are replayed: identity, super property and consent calls
 *   before the first pageview, capture calls after it.
 * - data-project-key instead of data-website-id resolves the website through
 *   /api/tracker-config?key= (response must carry `websiteId`).
 * - Sends use text/plain with the cache token in the body to avoid a CORS preflight.
 */
export const TRACKER_SCRIPT = String.raw`(function(){'use strict';
var t=window,d=document,l=location,nv=navigator,me=d.currentScript,k='flareboard.cache',idKey='flareboard.distinct_id',anonKey='flareboard.anon_id',propsKey='flareboard.props',optKey='flareboard.opt_out',lastUrl='',hmRate=0.1,hmOn=true,featureFlags=[],surveys=[],flagReady=null,flagExposures={},flagEvalCache={},scrollKey='flareboard.scroll',cacheReady=null,vitalsStarted=0,cfg=null,cfgDone=0,resolvedId=null,held=[],acHeld=[],aliasLater=null,flagCbs=[],flagsLoaded=0,pg=null,blockedPv=0,api;
var SENS=/pass(word|wd|code|phrase)?([^a-z]|$)|pwd|secret|token|(^|[^a-z])(otp|ssn|pin|cvc|cvv|csc|iban)([^a-z]|$)|one.?time|social.?sec|credit.?card|card.?(num|no([^a-z]|$))|cc.?(num|exp)|routing.?(num|no)|account.?(num|no([^a-z]|$))/i;
function own(o,a){return Object.prototype.hasOwnProperty.call(o,a)}
function store(kind){var m={};function x(){return t[kind]}return{getItem:function(a){var v=null;try{v=x().getItem(a)}catch(_){}return v!=null?v:own(m,a)?m[a]:null},setItem:function(a,b){try{x().setItem(a,b);delete m[a]}catch(_){m[a]=String(b)}},removeItem:function(a){try{x().removeItem(a)}catch(_){}delete m[a]}}}
var s=store('sessionStorage'),ls=store('localStorage');
function scriptEl(){if(me)return me;return d.querySelector('script[data-website-id],script[data-project-key]')}
function attr(a){var el=scriptEl();return el?el.getAttribute(a):null}
function boolAttr(a){var v=attr(a);return v==null?null:v!=='false'}
function postBody(type,payload){var o={type:type,payload:payload},c=s.getItem(k);if(c)o.cache=c;return JSON.stringify(o)}
function p(u,type,payload){return fetch(u,{method:'POST',headers:{'Content-Type':'text/plain'},body:postBody(type,payload),keepalive:true})}
function isHashRoute(h){return h.length>2&&h.charAt(1)==='/'}
function appPath(){var h=l.hash;if(isHashRoute(h)){var q=h.indexOf('?'),qs=[l.search.slice(1),q>=0?h.slice(q+1):''].filter(Boolean).join('&');return(q>=0?h.slice(1,q):h.slice(1))+(qs?'?'+qs:'')}return l.pathname+l.search}
function routeKey(){var h=l.hash;return l.pathname+l.search+(isHashRoute(h)?h:'')}
function r(){return{width:t.innerWidth+'x'+t.innerHeight,language:navigator.language,screen:screen.width+'x'+screen.height,title:d.title,hostname:l.hostname,url:appPath(),referrer:d.referrer}}
function ingestOrigin(){var el=scriptEl();if(el&&el.src)try{return new URL(el.src).origin}catch(_){}return l.protocol+'//'+l.host}
function websiteId(a){var el=a||scriptEl();return(el&&el.getAttribute('data-website-id'))||resolvedId}
function newId(){var c=t.crypto,b=new Uint8Array(16),h='',i;if(c&&c.randomUUID)return c.randomUUID();if(c&&c.getRandomValues)c.getRandomValues(b);else for(i=0;i<16;i++)b[i]=Math.random()*256|0;b[6]=b[6]&15|64;b[8]=b[8]&63|128;for(i=0;i<16;i++)h+=(b[i]+256).toString(16).slice(1)+(i===3||i===5||i===7||i===9?'-':'');return h}
function identifiedId(){return ls.getItem(idKey)||s.getItem(idKey)||''}
function setDistinctId(id){if(!id)return;ls.setItem(idKey,String(id));s.setItem(idKey,String(id))}
function clearDistinctId(){ls.removeItem(idKey);s.removeItem(idKey)}
function persistMode(){if(attr('data-persistence')==='false')return false;if(cfg)return cfg.ps;return ls.getItem(anonKey)?true:null}
function anonId(){var m=persistMode(),a;if(m===false)return'';a=(m?ls.getItem(anonKey):'')||s.getItem(anonKey);if(!a){a=newId();s.setItem(anonKey,a)}if(m&&ls.getItem(anonKey)!==a)ls.setItem(anonKey,a);return a}
function getDistinctId(){return identifiedId()||anonId()}
function ids(o){var u=identifiedId(),a=u?'':anonId();if(!o.id&&(u||a))o.id=u||a;if(a&&o.id===a)o.anonymousId=a;return o}
function applyPersist(){if(!cfg)return;var sp;if(!cfg.ps){ls.removeItem(anonKey);s.removeItem(anonKey);sp=ls.getItem(propsKey);if(sp){s.setItem(propsKey,sp);ls.removeItem(propsKey)}}else if(attr('data-persistence')!=='false'){anonId();sp=s.getItem(propsKey);if(sp&&!ls.getItem(propsKey)){ls.setItem(propsKey,sp);s.removeItem(propsKey)}}}
function propStore(){return persistMode()?ls:s}
function props(){var v=propStore().getItem(propsKey);try{v=v?JSON.parse(v):{};return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}catch(_){return{}}}
function saveProps(o){var st=propStore(),x=JSON.stringify(o);if(x==='{}')st.removeItem(propsKey);else st.setItem(propsKey,x)}
function register(o,once){if(!o||typeof o!=='object')return;var p=props(),a;for(a in o)if(own(o,a)&&(!once||!own(p,a)))p[a]=o[a];saveProps(p)}
function unregister(a){var p=props();if(own(p,a)){delete p[a];saveProps(p)}}
function expo(){var o={},a;for(a in flagExposures)if(own(flagExposures,a))o['$feature/'+a]=String(flagExposures[a]);return o}
function withProps(o){var src=[o.data&&typeof o.data==='object'?o.data:{},expo(),props()],out={},c=0,i,a;for(i=0;i<3;i++)for(a in src[i])if(own(src[i],a)&&!own(out,a)&&c<100){out[a]=src[i][a];c++}if(c)o.data=out;return o}
function dntSignal(){var v=nv.doNotTrack||t.doNotTrack||nv.msDoNotTrack;return v==='1'||v==='yes'||nv.globalPrivacyControl===true}
function dntMode(){var a=boolAttr('data-respect-dnt');return a!=null?a:cfg?cfg.dnt:cfgDone?false:null}
function acMode(){var a=boolAttr('data-autocapture');return a!=null?a:cfg?cfg.ac:cfgDone?false:null}
function plMode(){var a=boolAttr('data-pageleave');return a!=null?a:acMode()}
function optedOut(){return ls.getItem(optKey)==='1'||(dntSignal()&&dntMode()===true)}
function gated(){return dntSignal()&&dntMode()===null}
function hmCfgKey(w){return 'flareboard.hmCfg:'+w}
function hasCache(){return!!s.getItem(k)}
function parseResp(res){if(!res.ok)return res.text().then(function(){throw new Error('send '+res.status)});return res.json()}
function sendSafe(pr){return pr.catch(function(e){console.warn('[flareboard] send failed',e)})}
function applySendResp(x){x.cache&&s.setItem(k,x.cache);x.sessionId&&s.setItem('flareboard.sid',x.sessionId);x.visitId&&s.setItem('flareboard.vid',x.visitId);return x}
function send(type,payload){if(optedOut())return Promise.resolve();if(gated()){if(held.length<100)held.push([type,payload]);return Promise.resolve()}var go=function(){return p(ingestOrigin()+'/api/send',type,payload).then(parseResp).then(applySendResp)};if(hasCache())return sendSafe(go());if(!cacheReady){cacheReady=go().then(function(x){return x},function(e){cacheReady=null;throw e});return sendSafe(cacheReady)}return sendSafe(cacheReady.catch(function(){}).then(function(){return hasCache()?go():cacheReady}))}
function beacon(type,payload){if(optedOut()||gated())return;var u=ingestOrigin()+'/api/send',b=postBody(type,payload);try{if(nv.sendBeacon&&nv.sendBeacon(u,b))return}catch(_){}fetch(u,{method:'POST',headers:{'Content-Type':'text/plain'},body:b,keepalive:true}).catch(function(){})}
function settle(){var h=held,q=acHeld,i;held=[];acHeld=[];for(i=0;i<h.length;i++)send(h[i][0],h[i][1]);if(acMode())for(i=0;i<q.length;i++)send('event',q[i]);if(aliasLater&&persistMode())trackEvent(scriptEl(),{name:'$alias',data:{alias:aliasLater[0],distinctId:aliasLater[1]},tag:'identity'});aliasLater=null}
function buildEvent(a,extra){var w=websiteId(a);if(!w){console.warn('[flareboard] missing data-website-id');return null}var o=sdkMeta();o.website=w;Object.assign(o,extra||{});return withProps(o)}
function trackEvent(a,extra){var o=buildEvent(a,extra);if(!o)return;if(extra&&extra.name)setTimeout(function(){showSurvey(extra.name)},200);return send('event',o)}
function newPage(){var now=Date.now();pg={u:appPath(),ti:d.title,ms:0,at:now,vis:d.visibilityState!=='hidden',sc:0,n:0,tok:10,tt:now,lk:'',lt:0,left:0}}
function visTick(){if(!pg)return;var now=Date.now();if(pg.vis)pg.ms+=now-pg.at;pg.at=now;pg.vis=d.visibilityState!=='hidden'}
function leavePage(unloading){if(!pg||pg.left)return;visTick();pg.left=1;if(plMode()!==true)return;try{pg.sc=Math.max(pg.sc,scrollDepth())}catch(_){}var o=buildEvent(scriptEl(),{name:'$pageleave',url:pg.u,title:pg.ti,data:{$time_on_page:Math.round(pg.ms/1000),$max_scroll_depth:pg.sc}});if(!o)return;if(unloading)beacon('event',o);else send('event',o)}
function pageview(){newPage();blockedPv=optedOut()?1:0;return trackEvent(scriptEl())}
function onRoute(){var u=routeKey();if(u!==lastUrl){lastUrl=u;leavePage(false);flagEvalCache={};var w=websiteId();if(w)prefetchTargetedFlags(w).then(flagsDone);pageview()}}
function setupSpa(){lastUrl=routeKey();var ps=history.pushState,rs=history.replaceState;history.pushState=function(){ps.apply(history,arguments);onRoute()};history.replaceState=function(){rs.apply(history,arguments);onRoute()};t.addEventListener('popstate',onRoute);t.addEventListener('hashchange',onRoute)}
function eventProps(el){var data={},i,a,n;for(i=0;i<el.attributes.length;i++){a=el.attributes[i];n=a.name;if(n==='data-flareboard-event'||n==='data-umami-event'||n==='data-flareboard-event-tag'||n==='data-umami-event-tag')continue;var m=n.match(/^data-(?:flareboard|umami)-event-(.+)$/);if(m)data[m[1]]=a.value}return data}
function fireDeclEvent(el){var ev=el.getAttribute('data-flareboard-event')||el.getAttribute('data-umami-event');if(!ev)return;var data=eventProps(el),tag=el.getAttribute('data-flareboard-event-tag')||el.getAttribute('data-umami-event-tag');trackEvent(scriptEl(),{name:ev,data:Object.keys(data).length?data:undefined,tag:tag||undefined})}
function onDeclClick(e){var el=e.target;while(el&&el!==d){if(el.getAttribute('data-flareboard-event')||el.getAttribute('data-umami-event')){fireDeclEvent(el);break}el=el.parentElement}}
function cls(el){var c=el.getAttribute('class');return c?String(c).split(/\s+/).filter(Boolean):[]}
function noCap(el){for(;el&&el.nodeType===1;el=el.parentElement)if(el.hasAttribute('data-fb-no-capture')||cls(el).indexOf('ph-no-capture')>=0)return true;return false}
function sensitive(el){if((el.getAttribute('type')||'').toLowerCase()==='password')return true;for(var i=0,at=el.attributes;i<at.length;i++)if(at[i].name!=='style'&&SENS.test(at[i].name+'='+at[i].value))return true;return false}
function skipText(el){return/^(input|select|textarea|option|script|style|noscript|template|svg)$/i.test(el.tagName)||noCap(el)||sensitive(el)}
function elText(el){var out='',c=0;function walk(x){for(var ch=x.firstChild;ch&&out.length<300&&c<300;ch=ch.nextSibling){c++;if(ch.nodeType===3)out+=' '+ch.nodeValue;else if(ch.nodeType===1&&!skipText(ch))walk(ch)}}walk(el);out=out.replace(/\s+/g,' ').trim()||(el.getAttribute('aria-label')||'').trim();out=out.slice(0,255);return/(\d[ -]?){13}|\d{3}-\d{2}-\d{4}|[^\s@]+@[^\s@]+\.[a-z]/i.test(out)?'':out}
function selector(el){var out=[],i=0,tg,id,c;for(;el&&el.nodeType===1&&i<6;i++,el=el.parentElement){tg=el.tagName.toLowerCase();if(tg==='body'||tg==='html')break;id=el.getAttribute('id');if(id&&/^[A-Za-z][\w-]*$/.test(id)){out.unshift(tg+'#'+id);break}c=cls(el).filter(function(x){return/^[A-Za-z_-][\w-]*$/.test(x)}).slice(0,3);out.unshift(tg+(c.length?'.'+c.join('.'):''))}return out.join(' > ')}
function elInfo(el){var tg=el.tagName.toLowerCase(),o={$el_tag:tg},c=cls(el).slice(0,10),id=el.getAttribute('id'),ty=el.getAttribute('type'),nm=el.getAttribute('name'),h=el.getAttribute('href'),sens=sensitive(el),field=/^(input|select|textarea)$/.test(tg),x;if(id)o.$el_id=id.slice(0,200);if(c.length)o.$el_classes=c.join(' ').slice(0,500);if(ty&&(tg==='input'||tg==='button'))o.$el_type=ty.toLowerCase().slice(0,30);if(nm&&!sens&&(field||tg==='form'))o.$el_name=nm.slice(0,200);if(!sens&&!field&&tg!=='form'){x=elText(el);if(x)o.$el_text=x}if(h&&tg==='a'&&!sens&&!/^\s*javascript:/i.test(h))o.$el_href=h.slice(0,500);o.$el_selector=selector(el);return o}
function acCapture(kind,el){var m=acMode(),info,key,now=Date.now(),o;if(m===false||!pg)return;info=elInfo(el);key=kind+'|'+info.$el_selector+'|'+(info.$el_text||'');pg.tok=Math.min(10,pg.tok+(now-pg.tt)/1000);pg.tt=now;if(key===pg.lk&&now-pg.lt<1000)return;pg.lt=now;pg.lk=key;if(pg.n>=100||pg.tok<1)return;pg.tok--;pg.n++;info.$event_type=kind;o=buildEvent(scriptEl(),{name:'$autocapture',data:info,tag:'autocapture'});if(!o)return;if(m)send('event',o);else if(acHeld.length<20)acHeld.push(o)}
function clickable(el){for(var i=0,tg,ty;el&&el.nodeType===1&&i<10;i++,el=el.parentElement){tg=el.tagName.toLowerCase();ty=(el.getAttribute('type')||'').toLowerCase();if(tg==='a'||tg==='button'||el.getAttribute('role')==='button'||(tg==='input'&&(ty==='submit'||ty==='button')))return el;if(tg==='body')break}return null}
function onAcClick(e){var el=clickable(e.target);if(el&&!noCap(el))acCapture('click',el)}
function onAcSubmit(e){var el=e.target;if(el&&el.tagName&&el.tagName.toLowerCase()==='form'&&!noCap(el))acCapture('submit',el)}
function onAcChange(e){var el=e.target,ty;if(!el||!el.tagName||!/^(input|select|textarea)$/i.test(el.tagName))return;ty=(el.getAttribute('type')||'').toLowerCase();if(ty==='password'||ty==='hidden'||noCap(el)||sensitive(el))return;acCapture('change',el)}
function safe(f){return function(e){try{f(e)}catch(_){}}}
function setupAutocapture(){d.addEventListener('click',safe(onAcClick),true);d.addEventListener('submit',safe(onAcSubmit),true);d.addEventListener('change',safe(onAcChange),true);d.addEventListener('visibilitychange',visTick);t.addEventListener('pagehide',function(){leavePage(true)})}
function hmSample(){return hmOn&&Math.random()<hmRate}
function sendHeatmap(payload){var w=websiteId();if(!w)return;var o=r();o.website=w;send('heatmap',Object.assign(o,payload))}
function sdkMeta(extra){var el=scriptEl(),o=Object.assign(r(),extra||{});ids(o);if(el){var rel=el.getAttribute('data-release'),env=el.getAttribute('data-environment');if(rel&&!o.release)o.release=rel;if(env&&!o.environment)o.environment=env}return o}
function normalizeError(err,extra){var o=sdkMeta(extra),e=err&&err.error?err.error:err,reason=err&&err.reason?err.reason:null,msg='Unknown error',name='Error',stack,src,ln,cn;if(e){if(typeof e==='string')msg=e;else{msg=e.message||String(e);name=e.name||name;stack=e.stack}}else if(reason){msg=reason.message||String(reason);name=reason.name||name;stack=reason.stack}if(err){src=err.filename||err.source;ln=err.lineno;cn=err.colno}o.message=o.message||msg;o.errorName=o.errorName||name;if(stack&&!o.stack)o.stack=String(stack).slice(0,12000);if(src&&!o.source)o.source=String(src);if(ln!=null&&!o.lineno)o.lineno=ln;if(cn!=null&&!o.colno)o.colno=cn;if(o.handled==null)o.handled=false;if(!o.severity)o.severity='error';return o}
function captureException(err,extra){var w=websiteId();if(!w)return;var o=normalizeError(err,extra);o.website=w;return send('error',withProps(o))}
function setupErrors(){t.addEventListener('error',function(e){if(e&&e.target&&e.target!==t)return;captureException(e,{handled:false})},true);t.addEventListener('unhandledrejection',function(e){captureException(e,{handled:false,message:e.reason&&e.reason.message?e.reason.message:String(e.reason||'Unhandled rejection'),errorName:e.reason&&e.reason.name?e.reason.name:'UnhandledRejection',stack:e.reason&&e.reason.stack?e.reason.stack:undefined})})}
function onHmClick(e){if(!hmSample())return;var vw=t.innerWidth,vh=t.innerHeight;if(!vw||!vh)return;sendHeatmap({kind:'click',x:Math.round(e.clientX),y:Math.round(e.clientY),viewportWidth:vw,viewportHeight:vh})}
function scrollDepth(){var docH=Math.max(d.body.scrollHeight,d.documentElement.scrollHeight),vh=t.innerHeight,st=t.scrollY||d.documentElement.scrollTop;return docH<=vh?100:Math.min(100,Math.round((st+vh)/docH*100))}
function onHmScroll(){var depth=scrollDepth(),path=appPath(),key=scrollKey+':'+path,prev=parseInt(s.getItem(key)||'0',10)||0;if(pg&&depth>pg.sc)pg.sc=depth;if(depth<=prev)return;s.setItem(key,String(depth));if(!hmSample())return;sendHeatmap({kind:'scroll',scrollDepth:depth})}
function setupHeatmap(){var scrollTimer;d.addEventListener('click',onHmClick,true);t.addEventListener('scroll',function(){clearTimeout(scrollTimer);scrollTimer=setTimeout(onHmScroll,400)},{passive:true})}
function applyCfg(c,w){if(c&&typeof c.heatmapSampleRate==='number')hmRate=c.heatmapSampleRate;if(c&&c.heatmapEnabled===false)hmOn=false;featureFlags=c&&Array.isArray(c.featureFlags)?c.featureFlags:[];surveys=c&&Array.isArray(c.surveys)?c.surveys:[];if(c&&typeof c.autocapture==='boolean')cfg={ac:c.autocapture,ps:c.persistence===true,dnt:c.respectDnt===true};if(w)s.setItem(hmCfgKey(w),JSON.stringify({rate:hmRate,on:hmOn,flags:featureFlags,surveys:surveys,ts:cfg,exp:Date.now()+6e4}))}
function loadHmConfig(a,pre){var el=a||scriptEl(),at=el&&el.getAttribute('data-heatmap-sample-rate'),w=websiteId(el),raw,c,fresh=0,pr;if(at!=null){var rv=parseFloat(at);if(!isNaN(rv))hmRate=Math.min(1,Math.max(0,rv))}if(!w)return Promise.resolve(featureFlags);raw=s.getItem(hmCfgKey(w));if(pre){applyCfg(pre,w);fresh=1}else if(raw){try{c=JSON.parse(raw);if(c.ts)cfg=c.ts;if(c.exp>Date.now()){hmRate=c.rate;hmOn=c.on;featureFlags=Array.isArray(c.flags)?c.flags:[];surveys=Array.isArray(c.surveys)?c.surveys:[];fresh=1}}catch(_){}}applyPersist();pr=fresh?Promise.resolve():fetch(ingestOrigin()+'/api/tracker-config?website='+encodeURIComponent(w)).then(function(x){if(!x.ok)throw new Error('config '+x.status);return x.json()}).then(function(cf){applyCfg(cf,w)});flagReady=pr.catch(function(){}).then(function(){cfgDone=1;applyPersist();settle();return prefetchTargetedFlags(w)}).then(function(){flagsDone();return featureFlags},function(){flagsDone();return featureFlags});return flagReady}
${FLAG_HASH_JS}
function flagByKey(key){for(var i=0;i<featureFlags.length;i++)if(featureFlags[i].key===key)return featureFlags[i];return null}
function flagValue(field){if(field==='path')return appPath();if(field==='url')return l.href;if(field==='hostname')return l.hostname;if(field==='referrer')return d.referrer;if(field==='language')return navigator.language||'';if(field==='userAgent')return navigator.userAgent||'';return null}
function evalContext(){var el=scriptEl(),o={path:appPath(),url:l.href,hostname:l.hostname,referrer:d.referrer,language:nv.language||'',userAgent:nv.userAgent||''},did=getDistinctId();if(did)o.distinctId=did;var sid=s.getItem('flareboard.sid'),vid=s.getItem('flareboard.vid');if(sid)o.sessionId=sid;if(vid)o.visitId=vid;if(el){var rel=el.getAttribute('data-release'),env=el.getAttribute('data-environment');if(rel)o.release=rel;if(env)o.environment=env}return o}
function prefetchTargetedFlags(w){var keys=[],i;for(i=0;i<featureFlags.length;i++)if(featureFlags[i]&&featureFlags[i].targeted)keys.push(featureFlags[i].key);if(!keys.length)return Promise.resolve(flagEvalCache);return fetch(ingestOrigin()+'/api/feature-flags/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({website:w,keys:keys,context:evalContext()})}).then(function(x){return x.json()}).then(function(body){flagEvalCache=body&&body.results?body.results:{};return flagEvalCache}).catch(function(){return flagEvalCache})}
function bucketId(){return getDistinctId()||s.getItem('flareboard.sid')||s.getItem('flareboard.vid')||'anonymous'}
function featureVariant(key,fallback){var f=flagByKey(key);if(!f)return fallback===undefined?false:fallback;if(!f.enabled)return 'control';if(f.targeted){if(own(flagEvalCache,key))return flagEvalCache[key];return 'control'}var pct=typeof f.rollout==='number'?f.rollout:100,sid=bucketId();if(pct<=0)return 'control';if(pct<100&&hashFlag(key+':'+sid)>=pct)return 'control';var vars=Array.isArray(f.variants)?f.variants:[];if(vars.length){var b=hashFlag(key+':variant:'+sid),sum=0,last='control';for(var i=0;i<vars.length;i++){var v=vars[i];if(!v||!v.key)continue;last=String(v.key);sum+=Math.max(0,Math.min(100,Number(v.weight||0)));if(b<sum)return last}return sum>=100?last:'control'}return 'test'}
function exposeFlag(key,variant){if(flagExposures[key])return;flagExposures[key]=String(variant);var data={'$feature_flag':key,'$feature_flag_response':String(variant)};data['$feature/'+key]=String(variant);trackEvent(scriptEl(),{name:'$feature_flag_called',data:data,tag:'feature_flag'})}
function getFeatureFlag(key,fallback){var v=featureVariant(key,fallback);if(flagByKey(key))exposeFlag(key,v);return v}
function isFeatureEnabled(key,fallback){var v=getFeatureFlag(key,fallback);return v===true||(v!==false&&v!=='control')}
function flagPayload(key){var f=flagByKey(key),v,vs,i;if(!f)return undefined;v=featureVariant(key);vs=Array.isArray(f.variants)?f.variants:[];for(i=0;i<vs.length;i++)if(vs[i]&&String(vs[i].key)===String(v))return vs[i].payload;return v==='test'?f.payload:undefined}
function flagSnapshot(){var on=[],vars={},pays={},i,f,v,py;for(i=0;i<featureFlags.length;i++){f=featureFlags[i];if(!f||!f.key)continue;v=featureVariant(f.key);vars[f.key]=v;if(v===true||(v!==false&&v!=='control'))on.push(f.key);py=flagPayload(f.key);if(py!==undefined)pays[f.key]=py}return[on,vars,pays]}
function callFlags(cb){var sn=flagSnapshot();try{cb(sn[0],sn[1],sn[2])}catch(e){console.warn('[flareboard] onFeatureFlags callback failed',e)}}
function flagsDone(){flagsLoaded=1;for(var i=0;i<flagCbs.length;i++)callFlags(flagCbs[i])}
function onFeatureFlags(cb){if(typeof cb!=='function')return function(){};flagCbs.push(cb);if(flagsLoaded)callFlags(cb);return function(){var i=flagCbs.indexOf(cb);if(i>=0)flagCbs.splice(i,1)}}
function surveyStorageKey(id){return 'flareboard.survey:'+id}
function surveyShownAt(id){var v=ls.getItem(surveyStorageKey(id))||s.getItem(surveyStorageKey(id));return v?Number(v)||1:0}
function markSurvey(id){var v=String(Date.now());ls.setItem(surveyStorageKey(id),v);s.setItem(surveyStorageKey(id),v)}
function surveyEligible(sv){var at=surveyShownAt(sv.id),rd=sv.repeatIntervalDays,now=Date.now();if(sv.endsAt!=null&&now>=sv.endsAt)return false;if(at&&(rd==null||now-at<rd*864e5))return false;return hashFlag('survey:'+sv.id+':'+bucketId())<(typeof sv.sampleRate==='number'?sv.sampleRate:100)}
function surveyRuleMatches(rule){if(!rule||!rule.field||!rule.operator)return false;var v=flagValue(rule.field);if(v==null)return false;var left=String(v).toLowerCase(),right=String(rule.value==null?'':rule.value).toLowerCase(),op=rule.operator;if(op==='equals')return left===right;if(op==='not_equals')return left!==right;if(op==='contains')return left.indexOf(right)>=0;if(op==='not_contains')return left.indexOf(right)<0;return false}
function surveyMatches(sv,eventName){var pth=appPath(),tr=sv&&sv.triggerPath,ev=sv&&sv.triggerEvent;if(ev&&ev!==eventName)return false;if(!ev&&eventName)return false;if(tr&&!(pth===tr||pth.indexOf(tr+'?')===0||pth.indexOf(tr+'/')===0))return false;var rules=sv&&Array.isArray(sv.displayRules)?sv.displayRules:[];for(var i=0;i<rules.length;i++)if(!surveyRuleMatches(rules[i]))return false;return true}
function pickSurvey(eventName){for(var i=0;i<surveys.length;i++){if(surveys[i]&&surveys[i].id&&surveyMatches(surveys[i],eventName)&&surveyEligible(surveys[i]))return surveys[i]}return null}
function submitSurvey(sv,body){var w=websiteId();if(!w)return Promise.resolve();return fetch(ingestOrigin()+'/api/surveys/response',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({website:w,surveyId:sv.id,sessionId:s.getItem('flareboard.sid'),visitId:s.getItem('flareboard.vid'),distinctId:getDistinctId()||null,urlPath:appPath()},body)),keepalive:true}).catch(function(){})}
function svQuestions(sv){if(sv.version===2&&Array.isArray(sv.questions)&&sv.questions.length)return sv.questions;var b={id:'q1',question:sv.question||sv.name||'Feedback',branching:[]},o=Array.isArray(sv.options)?sv.options:[];if(sv.type==='rating')b.type='rating';else if(sv.type==='choice'&&o.join()==='0,1,2,3,4,5,6,7,8,9,10'){b.type='rating';b.scale='nps'}else if(sv.type==='choice'&&o.length){b.type='single_choice';b.options=o}else b.type='open';return[b]}
function svCond(q,w,a){if(w.type==='any')return true;if(a===undefined)return false;if(w.type==='range')return typeof a==='number'&&a>=w.min&&a<=w.max;var vals=Array.isArray(a)?a:[String(a)],opts=Array.isArray(q.options)?q.options:[],i;if(w.value==='$other'){for(i=0;i<vals.length;i++)if(opts.indexOf(vals[i])<0)return true;return false}return vals.indexOf(w.value)>=0}
function svNext(qs,i,a){var q=qs[i],r,j,k;if(!q)return 'end';r=q.branching||[];for(j=0;j<r.length;j++){if(!r[j]||!svCond(q,r[j].when||{},a))continue;if(r[j].next==='end')return 'end';for(k=0;k<qs.length;k++)if(qs[k].id===r[j].next)break;if(k<qs.length&&k>i)return k;break}return i+1<qs.length?i+1:'end'}
function showSurvey(eventName){if(d.getElementById('flareboard-survey')||optedOut())return;var sv=pickSurvey(eventName);if(!sv)return;var delay=Math.min(60,Math.max(0,Number(sv.displayDelaySeconds||0)));if(delay>0){sv.displayDelaySeconds=0;setTimeout(function(){showSurvey(eventName)},delay*1000);return}renderSurvey(sv)}
function renderSurvey(sv){var qs=svQuestions(sv),ap=sv.appearance||{},pal=ap.colors||{},mq=t.matchMedia&&t.matchMedia('(prefers-color-scheme: dark)'),dark=ap.theme==='dark'||(ap.theme!=='light'&&!!(mq&&mq.matches)),c=(dark?pal.dark:pal.light)||{},bg=c.background||(dark?'#0a0a0a':'#ffffff'),fg=c.text||(dark?'#ededed':'#171717'),mu=c.mutedText||(dark?'#a0a0a0':'#4d4d4d'),bd=c.border||(dark?'#2e2e2e':'#eaeaea'),ac=c.accent||fg,at=c.accentText||bg,pos={'bottom-left':'left:18px;bottom:18px','top-right':'right:18px;top:18px','top-left':'left:18px;top:18px',center:'left:50%;top:50%;transform:translate(-50%,-50%)'}[ap.position]||'right:18px;bottom:18px',box=el('div',null,'position:fixed;'+pos+';z-index:2147483647;width:min(360px,calc(100vw - 36px));box-sizing:border-box;padding:18px;border:1px solid '+bd+';border-radius:12px;background:'+bg+';color:'+fg+';box-shadow:0 12px 32px rgba(0,0,0,.18);font:14px/1.45 system-ui,-apple-system,Segoe UI,sans-serif'),main=el('div'),x=btn('×'),idx=0,ans={},rid=newId(),done=0,prev=d.activeElement;
function el(tag,txt,css){var n=d.createElement(tag);if(txt!=null)n.textContent=txt;if(css)n.style.cssText=css;return n}
function btn(txt,primary){var b=el('button',txt,'border:1px solid '+(primary?ac:bd)+';border-radius:8px;background:'+(primary?ac:bg)+';color:'+(primary?at:fg)+';padding:8px 12px;font:inherit;cursor:pointer');b.type='button';return b}
function has(){for(var a in ans)if(own(ans,a))return true;return false}
function close(){var inside=box.contains(d.activeElement);box.remove();if(inside&&prev&&prev.focus)try{prev.focus()}catch(_){}}
function dismiss(){if(!done&&has())submitSurvey(sv,{answers:ans,responseId:rid,completed:false});done=1;close()}
function finish(){done=1;if(!has())return close();submitSurvey(sv,{answers:ans,responseId:rid,completed:true});trackEvent(scriptEl(),{name:'survey_response',data:{surveyId:sv.id},tag:'survey'});if(ap.showThankYou===false)return close();main.textContent='';var ty=el('div',ap.thankYouMessage||'Thank you!','font-weight:600;margin-right:24px');ty.setAttribute('role','status');main.appendChild(ty);x.focus();setTimeout(close,4000)}
function advance(v){var q=qs[idx],n;if(v!==undefined)ans[q.id]=v;n=svNext(qs,idx,v);if(n==='end')finish();else step(n)}
function step(i){var q=qs[i],focused=i>0||box.contains(d.activeElement),wrap=el('div',null,'display:grid;gap:6px'),acts=el('div',null,'display:flex;justify-content:flex-end;gap:8px;margin-top:12px'),go=btn(q.buttonText||(q.type==='link'?'Open link':i===qs.length-1?ap.submitText||'Submit':'Next'),1),get,first,h=el('div',q.question,'font-weight:600;margin:0 24px 6px 0'),multi=q.type==='multiple_choice',sel,lo,hi,v,row,ins,opts,oth,ta,sk,lb,o,lab,inp;idx=i;main.textContent='';h.id='fb-sv-q';main.appendChild(h);if(q.description)main.appendChild(el('div',q.description,'color:'+mu+';margin-bottom:8px'));main.appendChild(wrap);
if(q.type==='rating'){lo=q.scale==='nps'?0:1;hi=q.scale==='nps'?10:q.scale===10?10:5;row=el('div',null,'display:grid;grid-template-columns:repeat('+(hi-lo+1)+',1fr);gap:4px');row.setAttribute('role','group');row.setAttribute('aria-labelledby','fb-sv-q');wrap.appendChild(row);for(v=lo;v<=hi;v++)(function(v){var b=btn(String(v));b.style.padding='8px 0';b.setAttribute('aria-pressed','false');b.onclick=function(){var bs=row.childNodes,j,on;sel=v;for(j=0;j<bs.length;j++){on=bs[j]===b;bs[j].setAttribute('aria-pressed',String(on));bs[j].style.background=on?ac:bg;bs[j].style.color=on?at:fg}};row.appendChild(b);first=first||b})(v);if(q.lowerLabel||q.upperLabel){lb=el('div',null,'display:flex;justify-content:space-between;color:'+mu+';font-size:12px');lb.appendChild(el('span',q.lowerLabel||''));lb.appendChild(el('span',q.upperLabel||''));wrap.appendChild(lb)}get=function(){return sel}}
else if(q.type==='single_choice'||multi){ins=[];opts=(q.options||[]).slice();if(q.hasOther)opts.push(null);for(o=0;o<opts.length;o++){lab=el('label',null,'display:flex;gap:8px;align-items:center;cursor:pointer');inp=d.createElement('input');inp.type=multi?'checkbox':'radio';inp.name='fb-sv-'+q.id;lab.appendChild(inp);lab.appendChild(el('span',opts[o]==null?'Other':opts[o]));wrap.appendChild(lab);ins.push(inp);first=first||inp}if(q.hasOther){oth=el('input',null,'box-sizing:border-box;width:100%;padding:7px 9px;border:1px solid '+bd+';border-radius:8px;font:inherit;color:inherit;background:'+bg);oth.type='text';oth.maxLength=500;oth.setAttribute('aria-label','Other');oth.oninput=function(){ins[ins.length-1].checked=!!oth.value.trim()};wrap.appendChild(oth)}get=function(){var out=[],k,tx;for(k=0;k<ins.length;k++)if(ins[k].checked){if(opts[k]==null){tx=oth.value.trim();if(tx)out.push(tx.slice(0,500))}else out.push(opts[k])}return out.length?multi?out:out[0]:undefined}}
else if(q.type==='link')get=function(){return 'clicked'};
else{ta=el('textarea',null,'box-sizing:border-box;width:100%;resize:vertical;padding:8px 10px;border:1px solid '+bd+';border-radius:8px;font:inherit;color:inherit;background:'+bg);ta.rows=3;ta.maxLength=2000;ta.setAttribute('aria-labelledby','fb-sv-q');if(q.placeholder)ta.placeholder=q.placeholder;wrap.appendChild(ta);first=ta;get=function(){var tx=ta.value.trim();return tx?tx.slice(0,2000):undefined}}
if(q.optional||q.type==='link'){sk=btn('Skip');sk.onclick=function(){advance(undefined)};acts.appendChild(sk)}go.onclick=function(){var a;if(q.type==='link'&&/^https?:/i.test(q.url||''))try{t.open(q.url,'_blank','noopener')}catch(_){}a=get();if(a===undefined&&!q.optional){(first||go).focus();return}advance(a)};acts.appendChild(go);main.appendChild(acts);if(focused)(first||go).focus()}
box.id='flareboard-survey';box.setAttribute('data-fb-no-capture','');box.setAttribute('role','dialog');box.setAttribute('aria-labelledby','fb-sv-q');x.setAttribute('aria-label','Close');x.style.cssText='position:absolute;top:8px;right:10px;border:0;background:none;color:'+mu+';font-size:20px;line-height:1;cursor:pointer';x.onclick=dismiss;box.onkeydown=function(e){if(e&&e.key==='Escape')dismiss()};box.appendChild(x);box.appendChild(main);if(!d.body)return;d.body.appendChild(box);markSurvey(sv.id);step(0)}
function collectVitals(a){if(vitalsStarted||!t.PerformanceObserver)return;vitalsStarted=1;var w=websiteId(a);if(!w)return;try{var o=r();o.website=w;var m={},sent=0,clsV=0,obs=[];function readTtfb(){try{var n=t.performance.getEntriesByType('navigation')[0];if(n){var st=n.activationStart||0,v=n.responseStart-st;if(v>=0&&v<6e4)return Math.round(v)}}catch(_){}}function readFcp(){try{var p=t.performance.getEntriesByType('paint'),i;for(i=0;i<p.length;i++)if(p[i].name==='first-contentful-paint')return Math.round(p[i].startTime)}catch(_){}}function readLcp(){try{var e=t.performance.getEntriesByType('largest-contentful-paint');if(e.length)return Math.round(e[e.length-1].startTime)}catch(_){}}function has(){return m.lcp!=null||m.inp!=null||m.cls!=null||m.fcp!=null||m.ttfb!=null}function cleanup(){for(var i=0;i<obs.length;i++)try{obs[i].disconnect()}catch(_){}obs=[];d.removeEventListener('visibilitychange',onVis);t.removeEventListener('pagehide',onLeave)}function flush(){if(sent)return;if(m.ttfb==null)m.ttfb=readTtfb();if(m.fcp==null)m.fcp=readFcp();if(m.lcp==null)m.lcp=readLcp();if(!has())return;sent=1;if(m.lcp!=null)o.lcp=m.lcp;if(m.inp!=null)o.inp=m.inp;if(m.cls!=null)o.cls=m.cls;if(m.fcp!=null)o.fcp=m.fcp;if(m.ttfb!=null)o.ttfb=m.ttfb;send('performance',o);cleanup()}function onVis(){if(d.visibilityState==='hidden')flush()}function onLeave(){flush()}function addObs(ob){try{obs.push(ob)}catch(_){}}try{addObs(new PerformanceObserver(function(l){var e=l.getEntries();if(e.length)m.lcp=Math.round(e[e.length-1].startTime)}));obs[obs.length-1].observe({type:'largest-contentful-paint',buffered:true})}catch(_){}try{addObs(new PerformanceObserver(function(l){var e=l.getEntries(),i;for(i=0;i<e.length;i++)if(e[i].name==='first-contentful-paint')m.fcp=Math.round(e[i].startTime)}));obs[obs.length-1].observe({type:'paint',buffered:true})}catch(_){}try{addObs(new PerformanceObserver(function(l){var e=l.getEntries();if(e.length)m.inp=Math.round(e[e.length-1].duration)}));obs[obs.length-1].observe({type:'event',buffered:true,durationThreshold:40})}catch(_){}try{addObs(new PerformanceObserver(function(l){var e=l.getEntries(),i;for(i=0;i<e.length;i++){if(!e[i].hadRecentInput)clsV+=e[i].value}m.cls=Math.round(clsV*1e4)/1e4}));obs[obs.length-1].observe({type:'layout-shift',buffered:true})}catch(_){}m.ttfb=readTtfb();m.fcp=readFcp();setTimeout(flush,1e4);d.addEventListener('visibilitychange',onVis);t.addEventListener('pagehide',onLeave)}catch(_){}}
function identify(id,data){var w=websiteId(),prev,a,m;if(!w||!id)return;id=String(id);prev=identifiedId();m=persistMode();a=prev||m===false?'':anonId();setDistinctId(id);if(a&&a!==id){if(m)trackEvent(scriptEl(),{name:'$alias',data:{alias:a,distinctId:id},tag:'identity'});else aliasLater=[a,id]}return send('identify',{website:w,id:id,data:data||{}})}
function reset(){clearDistinctId();s.removeItem(k);s.removeItem('flareboard.sid');s.removeItem('flareboard.vid');cacheReady=null;flagExposures={};aliasLater=null;ls.removeItem(propsKey);s.removeItem(propsKey);ls.removeItem(anonKey);s.removeItem(anonKey)}
function optOut(){ls.setItem(optKey,'1');held=[];acHeld=[];s.removeItem(k);s.removeItem('flareboard.sid');s.removeItem('flareboard.vid');cacheReady=null}
function optIn(){ls.removeItem(optKey);if(blockedPv&&!optedOut()){blockedPv=0;pageview()}}
api={track:function(n,data,tag){return trackEvent(scriptEl(),{name:n,data:data||undefined,tag:tag||undefined})},identify:identify,alias:function(alias,distinctId){return trackEvent(scriptEl(),{name:'$alias',data:{alias:alias,distinctId:distinctId||getDistinctId()||null},tag:'identity'})},group:function(type,key,data){var w=websiteId();if(!w||!type||!key)return;return send('group',ids({website:w,groupType:String(type),groupKey:String(key),data:data||{}}))},reset:reset,register:function(o){register(o)},registerOnce:function(o){register(o,1)},unregister:function(a){unregister(String(a))},optOut:optOut,optIn:optIn,hasOptedOut:function(){return optedOut()},revenue:function(amount,currency,extra){return trackEvent(scriptEl(),Object.assign({revenue:amount,currency:currency||'USD'},extra||{}))},log:function(level,message,data){var w=websiteId();if(!w)return;var o=sdkMeta();o.website=w;o.level=level||'info';o.message=message||'';o.data=data||undefined;return send('log',withProps(o))},ai:function(data){var w=websiteId();if(!w)return;var o=sdkMeta(data||{});o.website=w;return send('ai',withProps(o))},captureException:function(error,extra){return captureException(error,Object.assign({handled:true},extra||{}))},page:function(){leavePage(false);return pageview()},getDistinctId:function(){return getDistinctId()},getSessionId:function(){return s.getItem('flareboard.sid')},getVisitId:function(){return s.getItem('flareboard.vid')},getFeatureFlag:function(key,fallback){return getFeatureFlag(key,fallback)},getFeatureFlagVariant:function(key,fallback){return getFeatureFlag(key,fallback)},isFeatureEnabled:function(key,fallback){return isFeatureEnabled(key,fallback)},getFeatureFlagPayload:function(key){return flagPayload(key)},onFeatureFlags:onFeatureFlags,featureFlagsReady:function(){return flagReady||Promise.resolve(featureFlags)},showSurvey:function(){return showSurvey()}};
var CAPTURE=['track','page','revenue','log','ai','captureException','showSurvey'];
function replay(q,capture){for(var i=0;i<q.length;i++){var c=q[i],m=c&&c[0];if(typeof api[m]!=='function'||(CAPTURE.indexOf(m)>=0)!==capture)continue;try{api[m].apply(api,c[1]||[])}catch(e){console.warn('[flareboard] queued '+m+' failed',e)}}}
function start(a,pre){var cf=loadHmConfig(a,pre),q=t.flareboard&&Array.isArray(t.flareboard._q)?t.flareboard._q:[];t.flareboard=api;t.Flareboard=api;replay(q,false);pageview();replay(q,true);setupSpa();d.addEventListener('click',onDeclClick,true);setupHeatmap();setupErrors();setupAutocapture();collectVitals(a);if(cf&&cf.then)cf.then(function(){setTimeout(showSurvey,600)});else setTimeout(showSurvey,800)}
function init(){var a=scriptEl(),key;if(websiteId(a))return start(a);key=a&&a.getAttribute('data-project-key');if(!key)return;fetch(ingestOrigin()+'/api/tracker-config?key='+encodeURIComponent(key)).then(function(x){if(!x.ok)throw new Error('config '+x.status);return x.json()}).then(function(c){if(c&&c.websiteId){resolvedId=String(c.websiteId);start(a,c)}}).catch(function(e){console.warn('[flareboard] could not resolve data-project-key',e)})}
init();
})();`;
