import type { LucideIcon } from 'lucide-react';
import {
  AlertTriangle,
  ArrowLeftRight,
  Bot,
  Building2,
  CalendarDays,
  CreditCard,
  Database,
  DollarSign,
  FileText,
  Filter,
  Flag,
  FlaskConical,
  Gauge,
  Globe,
  Grid3x3,
  History,
  Home,
  LayoutDashboard,
  LayoutGrid,
  Layers,
  ListChecks,
  Lightbulb,
  Link2,
  Magnet,
  MessageSquareText,
  MousePointerClick,
  NotebookPen,
  PlayCircle,
  Radio,
  Repeat,
  Route,
  ScrollText,
  Settings,
  Share,
  Share2,
  Shield,
  Tag,
  Target,
  TerminalSquare,
  UserRound,
  Users,
  UsersRound,
  Workflow,
} from 'lucide-react';

export const sidebarNavIcons = {
  dashboard: Home,
  websites: Globe,
  teams: Users,
  links: Link2,
  reports: FileText,
  insights: Lightbulb,
  boards: LayoutGrid,
  notebooks: NotebookPen,
  admin: Shield,
  billing: CreditCard,
  overview: LayoutDashboard,
  events: MousePointerClick,
  actions: ListChecks,
  sessions: History,
  realtime: Radio,
  performance: Gauge,
  compare: ArrowLeftRight,
  goals: Target,
  funnel: Filter,
  journeys: Route,
  retention: Repeat,
  stickiness: Magnet,
  replays: PlayCircle,
  heatmaps: Grid3x3,
  people: UserRound,
  groups: Building2,
  segments: Layers,
  cohorts: UsersRound,
  utm: Tag,
  revenue: DollarSign,
  attribution: Share2,
  annotations: CalendarDays,
  share: Share,
  settings: Settings,
  errors: AlertTriangle,
  flags: Flag,
  experiments: FlaskConical,
  surveys: MessageSquareText,
  logs: TerminalSquare,
  ai: Bot,
  workflows: Workflow,
  warehouse: Database,
  audit: ScrollText,
} as const satisfies Record<string, LucideIcon>;

export type SidebarNavIconName = keyof typeof sidebarNavIcons;

type SidebarNavIconProps = {
  name: SidebarNavIconName;
};

export function SidebarNavIcon({ name }: SidebarNavIconProps) {
  const Icon = sidebarNavIcons[name];
  return <Icon className="sidebar-link-icon" size={16} strokeWidth={2} aria-hidden />;
}
